# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbecbc113f35c1e15364f605ac74aef784a5e5af7d2595a7be3b38e79fb95a9c9cd333a6cf049db6aaf994fbada85f71205a0a1108dc44746fdcaed8997b79c0

test:
  secret_key_base: cb9cb7b9deaa5f9097712e4d7fd8d1c4f0a0a2d72ebca41204e0628ce7afce21b75f78d9ed76e8d4d80273fcaa07cd48f3250bff4e444b433282d90acee3b367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
